<a href="https://colab.research.google.com/github/Aditya-2005917/projects-DataScience/blob/main/Ecommerce_of_india_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [526]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')
df=pd.read_excel('/content/E-commerce.xlsx')
df.head(10)

,1Gender of respondent,2 How old are you?,3 Which city do you shop online from?,4 What is the Pin Code of where you shop online from?,5 Since How Long You are Shopping Online ?,6 How many times you have made an online purchase in the past 1 year?,7 How do you access the internet while shopping on-line?,8 Which device do you use to access the online shopping?,9 What is the screen size of your mobile device?\t\t\t\t\t\t,10 What is the operating system (OS) of your device?\t\t\t\t,11 What browser do you run on your device to access the website?\t\t\t,12 Which channel did you follow to arrive at your favorite online store for the first time?,"13 After first visit, how do you reach the online retail store?\t\t\t\t",14 How much time do you explore the e- retail store before making a purchase decision?,15 What is your preferred payment Option?\t\t\t\t\t,16 How frequently do you abandon (selecting an items and leaving without making payment) your shopping cart?\t\t\t\t\t\t\t,"17 Why did you abandon the “Bag”, “Shopping Cart”?\t\t\t\t\t",18 The content on the website must be easy to read and understand,19 Information on similar product to the one highlighted is important for product comparison,20 Complete information on listed seller and product being offered is important for purchase decision.,21 All relevant information on listed products must be stated clearly,22 Ease of navigation in website,23 Loading and processing speed,24 User friendly Interface of the website,25 Convenient Payment methods,26 Trust that the online retail store will fulfill its part of the transaction at the stipulated time,27 Empathy (readiness to assist with queries) towards the customers,28 Being able to guarantee the privacy of the customer,"29 Responsiveness, availability of several communication channels (email, online rep, twitter, phone etc.)",30 Online shopping gives monetary benefit and discounts,31 Enjoyment is derived from shopping online,32 Shopping online is convenient and flexible,33 Return and replacement policy of the e-tailer is important for purchase decision,34 Gaining access to loyalty programs is a benefit of shopping online,35 Displaying quality Information on the website improves satisfaction of customers,36 User derive satisfaction while shopping on a good quality website or application,37 Net Benefit derived from shopping online can lead to users satisfaction,38 User satisfaction cannot exist without trust,39 Offering a wide variety of listed product in several category,40 Provision of complete and relevant product information,41 Monetary savings,42 The Convenience of patronizing the online retailer,43 Shopping on the website gives you the sense of adventure,44 Shopping on your preferred e-tailer enhances your social status,45 You feel gratification shopping on your favorite e-tailer,46 Shopping on the website helps you fulfill certain roles,47 Getting value for money spent,"From the following, tick any (or all) of the online retailers you have shopped from;",Easy to use website or application,Visual appealing web-page layout,Wild variety of product on offer,"Complete, relevant description information of products",Fast loading website speed of website and application,Reliability of the website or application,Quickness to complete purchase,Availability of several payment options,Speedy order delivery,Privacy of customers’ information,Security of customer financial information,Perceived Trustworthiness,Presence of online assistance through multi-channel,"Longer time to get logged in (promotion, sales period)","Longer time in displaying graphics and photos (promotion, sales period)","Late declaration of price (promotion, sales period)","Longer page loading time (promotion, sales period)","Limited mode of payment on most products (promotion, sales period)",Longer delivery period,Change in website/Application design,Frequent disruption when moving from one page to another,Website is as efficient as before,Which of the Indian online retailer would you recommend to a friend?
0,Male,31-40 years,Delhi,110009,Above 4 years,31-40 times,Dial-up,Desktop,Others,Window/windows Mobile,Google chrome,Search Engine,Search Engine,6-10 mins,"E-wallets (Paytm, Freecharge etc.)",Sometimes,Lack of trust,Agree (4),Indifferent (3),Indifferent (3),Agree (4),Agree (4),Strongly disagree (1),Dis-agree (2),Dis-agree (2),Disagree (2),Strongly agree (5),Agree (4),Agree (4),indifferent (3),Strongly disagree (1),Dis-agree (2),Dis-agree (2),Agree (4),indifferent (3),Strongly agree (5),Agree (4),Strongly agree (5),indifferent (3),indifferent (3),Disagree (2),indifferent (3),Agree (4),Agree (4),Strongly agree (5),Agree (4),Strongly agree (5),"Amazon.in, Paytm.com",Paytm.com,Flipkart.com,Flipkart.com,Snapdeal.com,Snapdeal.com,Paytm.com,Paytm.com,Patym.com,Amazon.in,Amazon.in,Amazon.in,Flipkart.com,Paytm.com,Amazon.in,Amazon.in,Flipkart.com,Flipkart.com,Amazon.in,Paytm.com,Flipkart.com,Amazon.in,Amazon.in,Flipkart.com
1,Female,21-30 years,Delhi,110030,Above 4 years,41 times and above,Wi-Fi,Smartphone,4.7 inches,IOS/Mac,Google chrome,Search Engine,Via application,more than 15 mins,Credit/Debit cards,Very frequently,Promo code not applicable,Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),indifferent (3),indifferent (3),indifferent (3),Strongly agree (5),Strongly agree (5),Strongly agree (5),"Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Myntra.com","Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Myntra.com",Myntra.com,"Amazon.com, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com",Myntra.com,Myntra.com,Myntra.com,"Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com",Myntra.com,snapdeal.com,Snapdeal.com,Snapdeal.com,Snapdeal.com,Amazon.in,Myntra.com,"Amazon.in, Flipkart.com","Amazon.in, Myntra.com"
2,Female,21-30 years,Greater Noida,201308,3-4 years,41 times and above,Mobile Internet,Smartphone,5.5 inches,Android,Google chrome,Search Engine,Via application,11-15 mins,"E-wallets (Paytm, Freecharge etc.)",Sometimes,Promo code not applicable,Strongly agree (5),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Agree (4),Agree (4),indifferent (3),indifferent (3),Agree (4),"Amazon.in, Paytm.com, Myntra.com","Amazon.in, Paytm.com, Myntra.com","Amazon.in, Paytm.com, Myntra.com","Amazon.in, Myntra.com","Amazon.in, Paytm.com, Myntra.com","Amazon.in, Paytm.com","Amazon.in, Paytm.com, Myntra.com","Amazon.com, Paytm.com, Myntra.com","Patym.com, Myntra.com",Amazon.in,Amazon.in,"Amazon.in, Paytm.com, Myntra.com","Amazon.in, Myntra.com",Myntra.com,Myntra.com,Myntra.com,Myntra.com,Myntra.com,Amazon.in,Paytm.com,Paytm.com,Paytm.com,Amazon.in,"Amazon.in, Paytm.com, Myntra.com"
3,Male,21-30 years,Karnal,132001,3-4 years,Less than 10 times,Mobile Internet,Smartphone,5.5 inches,IOS/Mac,Safari,Search Engine,Search Engine,6-10 mins,Credit/Debit cards,Never,Better alternative offer,Agree (4),Agree (4),Indifferent (3),Agree (4),Strongly agree (5),Agree (4),Strongly agree (5),Strongly agree (5),Agree (4),Strongly agree (5),Strongly agree (5),Agree (4),Agree (4),indifferent (3),indifferent (3),Agree (4),indifferent (3),indifferent (3),Agree (4),indifferent (3),Agree (4),Agree (4),Agree (4),Strongly agree (5),Agree (4),Agree (4),Strongly agree (5),Agree (4),indifferent (3),Agree (4),"Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Paytm.com","Amazon.com, Flipkart.com, Paytm.com","Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal",Snapdeal.com,"Myntra.com, Snapdeal.com",Myntra.com,Paytm.com,Paytm.com,Paytm.com,"Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com, Paytm.com","Amazon.in, Flipkart.com"
4,Female,21-30 years,Bangalore,530068,2-3 years,11-20 times,Wi-Fi,Smartphone,4.7 inches,IOS/Mac,Safari,Content Marketing,Via application,more than 15 mins,Credit/Debit cards,Frequently,Better alternative offer,Strongly agree (5),Indifferent (3),Indifferent (3),Agree (4),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Strongly agree (5),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Dis-agree (2),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Agree (4),Strongly agree (5),Agree (4),indifferent (3),Strongly disagree (1),Strongly agree (5),Strongly disagree (1),Strongly agree (5),"Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...",Myntra.com,Myntra.com,"Amazon.in, Flipkart.com, Paytm.com, Myntra.com...",Amazon.in,"Amazon.in, Paytm.com, Myntra.com","Amazon.com, Flipkart.com, Paytm.com, Myntra.co...","Amazon.in, Flipkart.com, Patym.com, Myntra.com...",Amazon.in,"Amazon.in, Paytm.com",Paytm.com,"Amazon.in, Myntra.com","Amazon.in, Myntra.com","Flipkart.com, Paytm.com",Paytm.com,Paytm.com,Paytm.com,Snapdeal.com,Paytm.com,Amazon.in,Snapdeal.com,Paytm.com,"Amazon.in, Myntra.com"
5,Female,31-40 years,Noida,201308,Above 4 years,41 times and above,Wi-Fi,Smartphone,5.5 inches,Android,Google chrome,Search Engine,Via application,more than 15 mins,"E-wallets (Paytm, Freecharge etc.)",Frequently,Better alternative offer,Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),indifferent (3),indifferent (3),Agree (4),Strongly agree (5),"Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com, Paytm.com","Amazon.in, Flipkart.com, Paytm.com","Amazon.in, Paytm.com","Amazon.in, Flipkart.com, Paytm.com, Snapdeal.com",Paytm.com,"Amazon.in, Flipkart.com, Patym.com, Myntra.com...",Amazon.in,"Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com","Flipkart.com, Paytm.com, Snapdeal.com","Amazon.in, Paytm.com","Amazon.in, Paytm.com","Amazon.in, Paytm.com","Amazon.in, Paytm.com",Flipkart.com,Paytm.com,Flipkart.com,Amazon.in,"Amazon.in, Paytm.com"
6,Male,41-50 yaers,Delhi,110011,Above 4 years,31-40 times,Wi-Fi,Tablet,Others,Android,Google chrome,Display Adverts,Direct URL,more than 15 mins,Credit/Debit cards,Sometimes,Promo code not applicable,Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Strongly agree (5),Strongly agree (5),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),indifferent (3),Agree (4),Agree (4),indifferent (3),indifferent (3),Agree (4),Agree (4),Agree (4),"Amazon.in, Flipkart.com, Paytm.com, Snapdeal.com","Amazon.in, Flipkart.com, Paytm.com, Snapdeal.com","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...",Amazon.in,"Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.com, Flipkart.com, Paytm.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal","Amazon.in, Flipkart.com, Snapdeal.com",Amazon.in,Myntra.com,Myntra.com,Flipkart.com,Snapdeal.com,Myntra.com,Myntra.com,Snapdeal.com,"Flipkart.com, Paytm.com, Myntra.com, snapdeal.com"
7,Male,41-50 yaers,Delhi,110018,3-4 years,Less than 10 times,Mobile Internet,Desktop,Others,Window/windows Mobile,Google chrome,Search Engine,E-mail,6-10 mins,Credit/Debit cards,Sometimes,Change in price,Strongly disagree (1),Dis-agree (2),Dis-agree (2),Strongly disagree (1),Strongly disagree (1),Dis-agree (2),Strongly disagree (1),Dis-agree (2),Disagree (2),Strongly disagree (1),indifferent (3),Strongly agree (5),Strongly disagree (1),Strongly disagree (1),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Strongly disagree (1),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly disagree (1),Strongly disagree (1),Strongly disagree (1),Agree (4),"Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com, Paytm.com",Amazon.in,Amazon.com,"Amazon.in, Flipkart.com",Amazon.in,Paytm.com,Flipkart.com,Amazon.in,Amazon.in,"Amazon.in, Flipkart.com","Amazon.in, Flipkart.com",Paytm.com,"Amazon.in, Flipkart.com","Amazon.in, Flipkart.com",Flipkart.com,Amazon.in,Amazon.in,Amazon.in,Amazon.in
8,Female,Less than 20 years,Solan,173229,2-3 years,Less than 10 times,Wi-Fi,Smartphone,5.5 inches,Android,Google chrome,Search Engine,Direct URL,1-5 mins,Cash on delivery (CoD),Sometimes,No preferred mode of payment,Strongly agree (5),Agree (4),Strongly agree (5),Agree (4),Agree (4),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Strongly agree (5),Agree (4),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Agree (4),Agree (4),Agree (4),indifferent (3),indifferent (3),Agree (4),indifferent (3),"Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Flipkart.com, Myntra.com, Snapdeal","Flipkart.com, Myntra.com, Snapdeal.com","Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal",Amazon.in,"Amazon.in, Myntra.com, Snapdeal.com",Amazon.in,"Amazon.in, Snapdeal.com",Amazon.in,Amazon.in,Amazon.in,"Myntra.com, Snapdeal.com","Myntra.com, Snapdeal.com",Amazon.in
9,Female,31-40 years,Delhi,110039,Less than 1 year,Less than 10 times,Wi-Fi,Laptop,Others,Window/windows Mobile,Google chrome,Search Engine,Search Engine,more than 15 mins,Cash on delivery (CoD),Sometimes,Lack of trust,Agree (4),Strongly agree (5),Agree (4),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Agree (4),Agree (4),Strongly agree (5),Agree (4),Agree (4),Agree (4),Strongly agree (5),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),indifferent (3),indifferent (3),indifferent (3),Agree (4),"Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.com, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com",Paytm.com,"Amazon.in, Flipkart.com",Paytm.com,Paytm.com,Snapdeal.com,Snapdeal.com,Myntra.com,Myntra.com,Flipkart.com,Flipkart.com

In [527]:
df.shape

(269, 71)

In [528]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 269 entries, 0 to 268
Data columns (total 71 columns):
 #   Column                                                                                                                                                                                                          Non-Null Count  Dtype
---  ------                                                                                                                                                                                                          --------------  -----
 0   1Gender of respondent                                                                                                                                                                                           269 non-null    object
 1   2 How old are you?                                                                                                                                                                                              269 non-null    object
 2   3 Which city do you shop online from?                                                                                                                                                                           269 non-null    object
 3   4 What is the Pin Code of where you shop online from?                                                                                                                                                           269 non-null    int64
 4   5 Since How Long You are Shopping Online ?                                                                                                                                                                      269 non-null    object
 5   6 How many times you have made an online purchase in the past 1 year?                                                                                                                                           269 non-null    object
 6   7 How do you access the internet while shopping on-line?                                                                                                                                                        269 non-null    object
 7   8 Which device do you use to access the online shopping?                                                                                                                                                        269 non-null    object
 8   9 What is the screen size of your mobile device?						                                                                                                                                                          269 non-null    object
 9   10 What is the operating system (OS) of your device?				                                                                                                                                                        269 non-null    object
 10  11 What browser do you run on your device to access the website?			                                                                                                                                             269 non-null    object
 11  12 Which channel did you follow to arrive at your favorite online store for the first time?                                                                                                                     269 non-null    object
 12  13 After first visit, how do you reach the online retail store?				                                                                                                                                             269 non-null    object
 13  14 How much time do you explore the e- retail store before making a purchase decision?                                                                                                                          269 non-null    object
 14  15 What is your preferred payment Option?					                                                                                                                                                                  269 non-null    object
 15  16 How frequently do you abandon (selecting an items and leaving without making payment) your shopping cart?							                                                                                             269 non-null    object
 16  17 Why did you abandon the “Bag”, “Shopping Cart”?					                                                                                                                                                         269 non-null    object
 17  18 The content on the website must be easy to read and understand                                                                                                                                               269 non-null    object
 18  19 Information on similar product to the one highlighted  is important for product comparison                                                                                                                   269 non-null    object
 19  20 Complete information on listed seller and product being offered is important for purchase decision.                                                                                                          269 non-null    object
 20  21 All relevant information on listed products must be stated clearly                                                                                                                                           269 non-null    object
 21  22 Ease of navigation in website                                                                                                                                                                                269 non-null    object
 22  23 Loading and processing speed                                                                                                                                                                                 269 non-null    object
 23  24 User friendly Interface of the website                                                                                                                                                                       269 non-null    object
 24  25 Convenient Payment methods                                                                                                                                                                                   269 non-null    object
 25  26 Trust that the online retail store will fulfill its part of the transaction at the stipulated time                                                                                                           269 non-null    object
 26  27 Empathy (readiness to assist with queries) towards the customers                                                                                                                                             269 non-null    object
 27  28 Being able to guarantee the privacy of the customer                                                                                                                                                          269 non-null    object
 28  29 Responsiveness, availability of several communication channels (email, online rep, twitter, phone etc.)                                                                                                      269 non-null    object
 29  30 Online shopping gives monetary benefit and discounts                                                                                                                                                         269 non-null    object
 30  31 Enjoyment is derived from shopping online                                                                                                                                                                    269 non-null    object
 31  32 Shopping online is convenient and flexible                                                                                                                                                                   269 non-null    object
 32  33 Return and replacement policy of the e-tailer is important for purchase decision                                                                                                                             269 non-null    object
 33  34 Gaining access to loyalty programs is a benefit of shopping online                                                                                                                                           269 non-null    object
 34  35 Displaying quality Information on the website improves satisfaction of customers                                                                                                                             269 non-null    object
 35  36 User derive satisfaction while shopping on a good quality website or application                                                                                                                             269 non-null    object
 36  37 Net Benefit derived from shopping online can lead to users satisfaction                                                                                                                                      269 non-null    object
 37  38 User satisfaction cannot exist without trust                                                                                                                                                                 269 non-null    object
 38  39 Offering a wide variety of listed product in several category                                                                                                                                                269 non-null    object
 39  40 Provision of complete and relevant product information                                                                                                                                                       269 non-null    object
 40  41 Monetary savings                                                                                                                                                                                             269 non-null    object
 41  42 The Convenience of patronizing the online retailer                                                                                                                                                           269 non-null    object
 42  43 Shopping on the website gives you the sense of adventure                                                                                                                                                     269 non-null    object
 43  44 Shopping on your preferred e-tailer enhances your social status                                                                                                                                              269 non-null    object
 44  45 You feel gratification shopping on your favorite e-tailer                                                                                                                                                    269 non-null    object
 45  46 Shopping on the website helps you fulfill certain roles                                                                                                                                                      269 non-null    object
 46  47 Getting value for money spent                                                                                                                                                                                269 non-null    object
 47  From the following, tick any (or all) of the online retailers you have shopped from;                                                                                                                            269 non-null    object
 48  Easy to use website or application                                                                                                                                                                              269 non-null    object
 49  Visual appealing web-page layout                                                                                                                                                                                269 non-null    object
 50  Wild variety of product on offer                                                                                                                                                                                269 non-null    object
 51  Complete, relevant description information of products                                                                                                                                                          269 non-null    object
 52  Fast loading website speed of website and application                                                                                                                                                           269 non-null    object
 53  Reliability of the website or application                                                                                                                                                                       269 non-null    object
 54  Quickness to complete purchase                                                                                                                                                                                  269 non-null    object
 55  Availability of several payment options                                                                                                                                                                         269 non-null    object
 56  Speedy order delivery                                                                                                                                                                                           269 non-null    object
 57  Privacy of customers’ information                                                                                                                                                                               269 non-null    object
 58  Security of customer financial information                                                                                                                                                                      269 non-null    object
 59  Perceived Trustworthiness                                                                                                                                                                                       269 non-null    object
 60  Presence of online assistance through multi-channel                                                                                                                                                             269 non-null    object
 61  Longer time to get logged in (promotion, sales period)                                                                                                                                                          269 non-null    object
 62  Longer time in displaying graphics and photos (promotion, sales period)                                                                                                                                         269 non-null    object
 63  Late declaration of price (promotion, sales period)                                                                                                                                                             269 non-null    object
 64  Longer page loading time (promotion, sales period)                                                                                                                                                              269 non-null    object
 65  Limited mode of payment on most products (promotion, sales period)                                                                                                                                              269 non-null    object
 66  Longer delivery period                                                                                                                                                                                          269 non-null    object
 67  Change in website/Application design                                                                                                                                                                            269 non-null    object
 68  Frequent disruption when moving from one page to another                                                                                                                                                        269 non-null    object
 69  Website is as efficient as before                                                                                                                                                                               269 non-null    object
 70  Which of the Indian online retailer would you recommend to a friend?                                                                                                                                            269 non-null    object
dtypes: int64(1), object(70)
memory usage: 149.3+ KB

In [529]:
df.dtypes

1Gender of respondent                                                                                                                                                                                                  object
2 How old are you?                                                                                                                                                                                                     object
3 Which city do you shop online from?                                                                                                                                                                                  object
4 What is the Pin Code of where you shop online from?                                                                                                                                                                   int64
5 Since How Long You are Shopping Online ?                                                                                                                                                                             object
6 How many times you have made an online purchase in the past 1 year?                                                                                                                                                  object
7 How do you access the internet while shopping on-line?                                                                                                                                                               object
8 Which device do you use to access the online shopping?                                                                                                                                                               object
9 What is the screen size of your mobile device?\t\t\t\t\t\t                                                                                                                                                           object
10 What is the operating system (OS) of your device?\t\t\t\t                                                                                                                                                           object
11 What browser do you run on your device to access the website?\t\t\t                                                                                                                                                 object
12 Which channel did you follow to arrive at your favorite online store for the first time?                                                                                                                            object
13 After first visit, how do you reach the online retail store?\t\t\t\t                                                                                                                                                object
14 How much time do you explore the e- retail store before making a purchase decision?                                                                                                                                 object
15 What is your preferred payment Option?\t\t\t\t\t                                                                                                                                                                    object
16 How frequently do you abandon (selecting an items and leaving without making payment) your shopping cart?\t\t\t\t\t\t\t                                                                                             object
17 Why did you abandon the “Bag”, “Shopping Cart”?\t\t\t\t\t                                                                                                                                                           object
18 The content on the website must be easy to read and understand                                                                                                                                                      object
19 Information on similar product to the one highlighted  is important for product comparison                                                                                                                          object
20 Complete information on listed seller and product being offered is important for purchase decision.                                                                                                                 object
21 All relevant information on listed products must be stated clearly                                                                                                                                                  object
22 Ease of navigation in website                                                                                                                                                                                       object
23 Loading and processing speed                                                                                                                                                                                        object
24 User friendly Interface of the website                                                                                                                                                                              object
25 Convenient Payment methods                                                                                                                                                                                          object
26 Trust that the online retail store will fulfill its part of the transaction at the stipulated time                                                                                                                  object
27 Empathy (readiness to assist with queries) towards the customers                                                                                                                                                    object
28 Being able to guarantee the privacy of the customer                                                                                                                                                                 object
29 Responsiveness, availability of several communication channels (email, online rep, twitter, phone etc.)                                                                                                             object
30 Online shopping gives monetary benefit and discounts                                                                                                                                                                object
31 Enjoyment is derived from shopping online                                                                                                                                                                           object
32 Shopping online is convenient and flexible                                                                                                                                                                          object
33 Return and replacement policy of the e-tailer is important for purchase decision                                                                                                                                    object
34 Gaining access to loyalty programs is a benefit of shopping online                                                                                                                                                  object
35 Displaying quality Information on the website improves satisfaction of customers                                                                                                                                    object
36 User derive satisfaction while shopping on a good quality website or application                                                                                                                                    object
37 Net Benefit derived from shopping online can lead to users satisfaction                                                                                                                                             object
38 User satisfaction cannot exist without trust                                                                                                                                                                        object
39 Offering a wide variety of listed product in several category                                                                                                                                                       object
40 Provision of complete and relevant product information                                                                                                                                                              object
41 Monetary savings                                                                                                                                                                                                    object
42 The Convenience of patronizing the online retailer                                                                                                                                                                  object
43 Shopping on the website gives you the sense of adventure                                                                                                                                                            object
44 Shopping on your preferred e-tailer enhances your social status                                                                                                                                                     object
45 You feel gratification shopping on your favorite e-tailer                                                                                                                                                           object
46 Shopping on the website helps you fulfill certain roles                                                                                                                                                             object
47 Getting value for money spent                                                                                                                                                                                       object
From the following, tick any (or all) of the online retailers you have shopped from;                                                                                                                                   object
Easy to use website or application                                                                                                                                                                                     object
Visual appealing web-page layout                                                                                                                                                                                       object
Wild variety of product on offer                                                                                                                                                                                       object
Complete, relevant description information of products                                                                                                                                                                 object
Fast loading website speed of website and application                                                                                                                                                                  object
Reliability of the website or application                                                                                                                                                                              object
Quickness to complete purchase                                                                                                                                                                                         object
Availability of several payment options                                                                                                                                                                                object
Speedy order delivery                                                                                                                                                                                                  object
Privacy of customers’ information                                                                                                                                                                                      object
Security of customer financial information                                                                                                                                                                             object
Perceived Trustworthiness                                                                                                                                                                                              object
Presence of online assistance through multi-channel                                                                                                                                                                    object
Longer time to get logged in (promotion, sales period)                                                                                                                                                                 object
Longer time in displaying graphics and photos (promotion, sales period)                                                                                                                                                object
Late declaration of price (promotion, sales period)                                                                                                                                                                    object
Longer page loading time (promotion, sales period)                                                                                                                                                                     object
Limited mode of payment on most products (promotion, sales period)                                                                                                                                                     object
Longer delivery period                                                                                                                                                                                                 object
Change in website/Application design                                                                                                                                                                                   object
Frequent disruption when moving from one page to another                                                                                                                                                               object
Website is as efficient as before                                                                                                                                                                                      object
Which of the Indian online retailer would you recommend to a friend?                                                                                                                                                   object
dtype: object

In [530]:
pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows", None)

In [531]:
df.columns=df.columns.str.replace("/t","")

In [532]:
from string import digits
remove_digits = str.maketrans('', '', digits)
df.columns = df.columns.str.translate(remove_digits)

In [533]:
df.columns = df.columns.str.strip()

In [534]:
df.head()

,Gender of respondent,How old are you?,Which city do you shop online from?,What is the Pin Code of where you shop online from?,Since How Long You are Shopping Online ?,How many times you have made an online purchase in the past year?,How do you access the internet while shopping on-line?,Which device do you use to access the online shopping?,What is the screen size of your mobile device?,What is the operating system (OS) of your device?,What browser do you run on your device to access the website?,Which channel did you follow to arrive at your favorite online store for the first time?,"After first visit, how do you reach the online retail store?",How much time do you explore the e- retail store before making a purchase decision?,What is your preferred payment Option?,How frequently do you abandon (selecting an items and leaving without making payment) your shopping cart?,"Why did you abandon the “Bag”, “Shopping Cart”?",The content on the website must be easy to read and understand,Information on similar product to the one highlighted is important for product comparison,Complete information on listed seller and product being offered is important for purchase decision.,All relevant information on listed products must be stated clearly,Ease of navigation in website,Loading and processing speed,User friendly Interface of the website,Convenient Payment methods,Trust that the online retail store will fulfill its part of the transaction at the stipulated time,Empathy (readiness to assist with queries) towards the customers,Being able to guarantee the privacy of the customer,"Responsiveness, availability of several communication channels (email, online rep, twitter, phone etc.)",Online shopping gives monetary benefit and discounts,Enjoyment is derived from shopping online,Shopping online is convenient and flexible,Return and replacement policy of the e-tailer is important for purchase decision,Gaining access to loyalty programs is a benefit of shopping online,Displaying quality Information on the website improves satisfaction of customers,User derive satisfaction while shopping on a good quality website or application,Net Benefit derived from shopping online can lead to users satisfaction,User satisfaction cannot exist without trust,Offering a wide variety of listed product in several category,Provision of complete and relevant product information,Monetary savings,The Convenience of patronizing the online retailer,Shopping on the website gives you the sense of adventure,Shopping on your preferred e-tailer enhances your social status,You feel gratification shopping on your favorite e-tailer,Shopping on the website helps you fulfill certain roles,Getting value for money spent,"From the following, tick any (or all) of the online retailers you have shopped from;",Easy to use website or application,Visual appealing web-page layout,Wild variety of product on offer,"Complete, relevant description information of products",Fast loading website speed of website and application,Reliability of the website or application,Quickness to complete purchase,Availability of several payment options,Speedy order delivery,Privacy of customers’ information,Security of customer financial information,Perceived Trustworthiness,Presence of online assistance through multi-channel,"Longer time to get logged in (promotion, sales period)","Longer time in displaying graphics and photos (promotion, sales period)","Late declaration of price (promotion, sales period)","Longer page loading time (promotion, sales period)","Limited mode of payment on most products (promotion, sales period)",Longer delivery period,Change in website/Application design,Frequent disruption when moving from one page to another,Website is as efficient as before,Which of the Indian online retailer would you recommend to a friend?
0,Male,31-40 years,Delhi,110009,Above 4 years,31-40 times,Dial-up,Desktop,Others,Window/windows Mobile,Google chrome,Search Engine,Search Engine,6-10 mins,"E-wallets (Paytm, Freecharge etc.)",Sometimes,Lack of trust,Agree (4),Indifferent (3),Indifferent (3),Agree (4),Agree (4),Strongly disagree (1),Dis-agree (2),Dis-agree (2),Disagree (2),Strongly agree (5),Agree (4),Agree (4),indifferent (3),Strongly disagree (1),Dis-agree (2),Dis-agree (2),Agree (4),indifferent (3),Strongly agree (5),Agree (4),Strongly agree (5),indifferent (3),indifferent (3),Disagree (2),indifferent (3),Agree (4),Agree (4),Strongly agree (5),Agree (4),Strongly agree (5),"Amazon.in, Paytm.com",Paytm.com,Flipkart.com,Flipkart.com,Snapdeal.com,Snapdeal.com,Paytm.com,Paytm.com,Patym.com,Amazon.in,Amazon.in,Amazon.in,Flipkart.com,Paytm.com,Amazon.in,Amazon.in,Flipkart.com,Flipkart.com,Amazon.in,Paytm.com,Flipkart.com,Amazon.in,Amazon.in,Flipkart.com
1,Female,21-30 years,Delhi,110030,Above 4 years,41 times and above,Wi-Fi,Smartphone,4.7 inches,IOS/Mac,Google chrome,Search Engine,Via application,more than 15 mins,Credit/Debit cards,Very frequently,Promo code not applicable,Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),indifferent (3),indifferent (3),indifferent (3),Strongly agree (5),Strongly agree (5),Strongly agree (5),"Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Myntra.com","Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Myntra.com",Myntra.com,"Amazon.com, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com",Myntra.com,Myntra.com,Myntra.com,"Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com",Myntra.com,snapdeal.com,Snapdeal.com,Snapdeal.com,Snapdeal.com,Amazon.in,Myntra.com,"Amazon.in, Flipkart.com","Amazon.in, Myntra.com"
2,Female,21-30 years,Greater Noida,201308,3-4 years,41 times and above,Mobile Internet,Smartphone,5.5 inches,Android,Google chrome,Search Engine,Via application,11-15 mins,"E-wallets (Paytm, Freecharge etc.)",Sometimes,Promo code not applicable,Strongly agree (5),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Agree (4),Agree (4),indifferent (3),indifferent (3),Agree (4),"Amazon.in, Paytm.com, Myntra.com","Amazon.in, Paytm.com, Myntra.com","Amazon.in, Paytm.com, Myntra.com","Amazon.in, Myntra.com","Amazon.in, Paytm.com, Myntra.com","Amazon.in, Paytm.com","Amazon.in, Paytm.com, Myntra.com","Amazon.com, Paytm.com, Myntra.com","Patym.com, Myntra.com",Amazon.in,Amazon.in,"Amazon.in, Paytm.com, Myntra.com","Amazon.in, Myntra.com",Myntra.com,Myntra.com,Myntra.com,Myntra.com,Myntra.com,Amazon.in,Paytm.com,Paytm.com,Paytm.com,Amazon.in,"Amazon.in, Paytm.com, Myntra.com"
3,Male,21-30 years,Karnal,132001,3-4 years,Less than 10 times,Mobile Internet,Smartphone,5.5 inches,IOS/Mac,Safari,Search Engine,Search Engine,6-10 mins,Credit/Debit cards,Never,Better alternative offer,Agree (4),Agree (4),Indifferent (3),Agree (4),Strongly agree (5),Agree (4),Strongly agree (5),Strongly agree (5),Agree (4),Strongly agree (5),Strongly agree (5),Agree (4),Agree (4),indifferent (3),indifferent (3),Agree (4),indifferent (3),indifferent (3),Agree (4),indifferent (3),Agree (4),Agree (4),Agree (4),Strongly agree (5),Agree (4),Agree (4),Strongly agree (5),Agree (4),indifferent (3),Agree (4),"Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Paytm.com","Amazon.com, Flipkart.com, Paytm.com","Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal",Snapdeal.com,"Myntra.com, Snapdeal.com",Myntra.com,Paytm.com,Paytm.com,Paytm.com,"Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com, Paytm.com","Amazon.in, Flipkart.com"
4,Female,21-30 years,Bangalore,530068,2-3 years,11-20 times,Wi-Fi,Smartphone,4.7 inches,IOS/Mac,Safari,Content Marketing,Via application,more than 15 mins,Credit/Debit cards,Frequently,Better alternative offer,Strongly agree (5),Indifferent (3),Indifferent (3),Agree (4),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Strongly agree (5),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Dis-agree (2),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Agree (4),Strongly agree (5),Agree (4),indifferent (3),Strongly disagree (1),Strongly agree (5),Strongly disagree (1),Strongly agree (5),"Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...",Myntra.com,Myntra.com,"Amazon.in, Flipkart.com, Paytm.com, Myntra.com...",Amazon.in,"Amazon.in, Paytm.com, Myntra.com","Amazon.com, Flipkart.com, Paytm.com, Myntra.co...","Amazon.in, Flipkart.com, Patym.com, Myntra.com...",Amazon.in,"Amazon.in, Paytm.com",Paytm.com,"Amazon.in, Myntra.com","Amazon.in, Myntra.com","Flipkart.com, Paytm.com",Paytm.com,Paytm.com,Paytm.com,Snapdeal.com,Paytm.com,Amazon.in,Snapdeal.com,Paytm.com,"Amazon.in, Myntra.com"

In [535]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 269 entries, 0 to 268
Data columns (total 71 columns):
 #   Column                                                                                                     Non-Null Count  Dtype
---  ------                                                                                                     --------------  -----
 0   Gender of respondent                                                                                       269 non-null    object
 1   How old are you?                                                                                           269 non-null    object
 2   Which city do you shop online from?                                                                        269 non-null    object
 3   What is the Pin Code of where you shop online from?                                                        269 non-null    int64
 4   Since How Long You are Shopping Online ?                                                                   269 non-null    object
 5   How many times you have made an online purchase in the past  year?                                         269 non-null    object
 6   How do you access the internet while shopping on-line?                                                     269 non-null    object
 7   Which device do you use to access the online shopping?                                                     269 non-null    object
 8   What is the screen size of your mobile device?                                                             269 non-null    object
 9   What is the operating system (OS) of your device?                                                          269 non-null    object
 10  What browser do you run on your device to access the website?                                              269 non-null    object
 11  Which channel did you follow to arrive at your favorite online store for the first time?                   269 non-null    object
 12  After first visit, how do you reach the online retail store?                                               269 non-null    object
 13  How much time do you explore the e- retail store before making a purchase decision?                        269 non-null    object
 14  What is your preferred payment Option?                                                                     269 non-null    object
 15  How frequently do you abandon (selecting an items and leaving without making payment) your shopping cart?  269 non-null    object
 16  Why did you abandon the “Bag”, “Shopping Cart”?                                                            269 non-null    object
 17  The content on the website must be easy to read and understand                                             269 non-null    object
 18  Information on similar product to the one highlighted  is important for product comparison                 269 non-null    object
 19  Complete information on listed seller and product being offered is important for purchase decision.        269 non-null    object
 20  All relevant information on listed products must be stated clearly                                         269 non-null    object
 21  Ease of navigation in website                                                                              269 non-null    object
 22  Loading and processing speed                                                                               269 non-null    object
 23  User friendly Interface of the website                                                                     269 non-null    object
 24  Convenient Payment methods                                                                                 269 non-null    object
 25  Trust that the online retail store will fulfill its part of the transaction at the stipulated time         269 non-null    object
 26  Empathy (readiness to assist with queries) towards the customers                                           269 non-null    object
 27  Being able to guarantee the privacy of the customer                                                        269 non-null    object
 28  Responsiveness, availability of several communication channels (email, online rep, twitter, phone etc.)    269 non-null    object
 29  Online shopping gives monetary benefit and discounts                                                       269 non-null    object
 30  Enjoyment is derived from shopping online                                                                  269 non-null    object
 31  Shopping online is convenient and flexible                                                                 269 non-null    object
 32  Return and replacement policy of the e-tailer is important for purchase decision                           269 non-null    object
 33  Gaining access to loyalty programs is a benefit of shopping online                                         269 non-null    object
 34  Displaying quality Information on the website improves satisfaction of customers                           269 non-null    object
 35  User derive satisfaction while shopping on a good quality website or application                           269 non-null    object
 36  Net Benefit derived from shopping online can lead to users satisfaction                                    269 non-null    object
 37  User satisfaction cannot exist without trust                                                               269 non-null    object
 38  Offering a wide variety of listed product in several category                                              269 non-null    object
 39  Provision of complete and relevant product information                                                     269 non-null    object
 40  Monetary savings                                                                                           269 non-null    object
 41  The Convenience of patronizing the online retailer                                                         269 non-null    object
 42  Shopping on the website gives you the sense of adventure                                                   269 non-null    object
 43  Shopping on your preferred e-tailer enhances your social status                                            269 non-null    object
 44  You feel gratification shopping on your favorite e-tailer                                                  269 non-null    object
 45  Shopping on the website helps you fulfill certain roles                                                    269 non-null    object
 46  Getting value for money spent                                                                              269 non-null    object
 47  From the following, tick any (or all) of the online retailers you have shopped from;                       269 non-null    object
 48  Easy to use website or application                                                                         269 non-null    object
 49  Visual appealing web-page layout                                                                           269 non-null    object
 50  Wild variety of product on offer                                                                           269 non-null    object
 51  Complete, relevant description information of products                                                     269 non-null    object
 52  Fast loading website speed of website and application                                                      269 non-null    object
 53  Reliability of the website or application                                                                  269 non-null    object
 54  Quickness to complete purchase                                                                             269 non-null    object
 55  Availability of several payment options                                                                    269 non-null    object
 56  Speedy order delivery                                                                                      269 non-null    object
 57  Privacy of customers’ information                                                                          269 non-null    object
 58  Security of customer financial information                                                                 269 non-null    object
 59  Perceived Trustworthiness                                                                                  269 non-null    object
 60  Presence of online assistance through multi-channel                                                        269 non-null    object
 61  Longer time to get logged in (promotion, sales period)                                                     269 non-null    object
 62  Longer time in displaying graphics and photos (promotion, sales period)                                    269 non-null    object
 63  Late declaration of price (promotion, sales period)                                                        269 non-null    object
 64  Longer page loading time (promotion, sales period)                                                         269 non-null    object
 65  Limited mode of payment on most products (promotion, sales period)                                         269 non-null    object
 66  Longer delivery period                                                                                     269 non-null    object
 67  Change in website/Application design                                                                       269 non-null    object
 68  Frequent disruption when moving from one page to another                                                   269 non-null    object
 69  Website is as efficient as before                                                                          269 non-null    object
 70  Which of the Indian online retailer would you recommend to a friend?                                       269 non-null    object
dtypes: int64(1), object(70)
memory usage: 149.3+ KB

In [536]:
df.isnull().sum()

Gender of respondent                                                                                         0
How old are you?                                                                                             0
Which city do you shop online from?                                                                          0
What is the Pin Code of where you shop online from?                                                          0
Since How Long You are Shopping Online ?                                                                     0
How many times you have made an online purchase in the past  year?                                           0
How do you access the internet while shopping on-line?                                                       0
Which device do you use to access the online shopping?                                                       0
What is the screen size of your mobile device?                                                               0
What is the operating system (OS) of your device?                                                            0
What browser do you run on your device to access the website?                                                0
Which channel did you follow to arrive at your favorite online store for the first time?                     0
After first visit, how do you reach the online retail store?                                                 0
How much time do you explore the e- retail store before making a purchase decision?                          0
What is your preferred payment Option?                                                                       0
How frequently do you abandon (selecting an items and leaving without making payment) your shopping cart?    0
Why did you abandon the “Bag”, “Shopping Cart”?                                                              0
The content on the website must be easy to read and understand                                               0
Information on similar product to the one highlighted  is important for product comparison                   0
Complete information on listed seller and product being offered is important for purchase decision.          0
All relevant information on listed products must be stated clearly                                           0
Ease of navigation in website                                                                                0
Loading and processing speed                                                                                 0
User friendly Interface of the website                                                                       0
Convenient Payment methods                                                                                   0
Trust that the online retail store will fulfill its part of the transaction at the stipulated time           0
Empathy (readiness to assist with queries) towards the customers                                             0
Being able to guarantee the privacy of the customer                                                          0
Responsiveness, availability of several communication channels (email, online rep, twitter, phone etc.)      0
Online shopping gives monetary benefit and discounts                                                         0
Enjoyment is derived from shopping online                                                                    0
Shopping online is convenient and flexible                                                                   0
Return and replacement policy of the e-tailer is important for purchase decision                             0
Gaining access to loyalty programs is a benefit of shopping online                                           0
Displaying quality Information on the website improves satisfaction of customers                             0
User derive satisfaction while shopping on a good quality website or application                             0
Net Benefit derived from shopping online can lead to users satisfaction                                      0
User satisfaction cannot exist without trust                                                                 0
Offering a wide variety of listed product in several category                                                0
Provision of complete and relevant product information                                                       0
Monetary savings                                                                                             0
The Convenience of patronizing the online retailer                                                           0
Shopping on the website gives you the sense of adventure                                                     0
Shopping on your preferred e-tailer enhances your social status                                              0
You feel gratification shopping on your favorite e-tailer                                                    0
Shopping on the website helps you fulfill certain roles                                                      0
Getting value for money spent                                                                                0
From the following, tick any (or all) of the online retailers you have shopped from;                         0
Easy to use website or application                                                                           0
Visual appealing web-page layout                                                                             0
Wild variety of product on offer                                                                             0
Complete, relevant description information of products                                                       0
Fast loading website speed of website and application                                                        0
Reliability of the website or application                                                                    0
Quickness to complete purchase                                                                               0
Availability of several payment options                                                                      0
Speedy order delivery                                                                                        0
Privacy of customers’ information                                                                            0
Security of customer financial information                                                                   0
Perceived Trustworthiness                                                                                    0
Presence of online assistance through multi-channel                                                          0
Longer time to get logged in (promotion, sales period)                                                       0
Longer time in displaying graphics and photos (promotion, sales period)                                      0
Late declaration of price (promotion, sales period)                                                          0
Longer page loading time (promotion, sales period)                                                           0
Limited mode of payment on most products (promotion, sales period)                                           0
Longer delivery period                                                                                       0
Change in website/Application design                                                                         0
Frequent disruption when moving from one page to another                                                     0
Website is as efficient as before                                                                            0
Which of the Indian online retailer would you recommend to a friend?                                         0
dtype: int64

In [537]:
df.nunique()

Gender of respondent                                                                                          2
How old are you?                                                                                              5
Which city do you shop online from?                                                                          11
What is the Pin Code of where you shop online from?                                                          39
Since How Long You are Shopping Online ?                                                                      5
How many times you have made an online purchase in the past  year?                                            6
How do you access the internet while shopping on-line?                                                        4
Which device do you use to access the online shopping?                                                        4
What is the screen size of your mobile device?                                                                4
What is the operating system (OS) of your device?                                                             3
What browser do you run on your device to access the website?                                                 4
Which channel did you follow to arrive at your favorite online store for the first time?                      3
After first visit, how do you reach the online retail store?                                                  5
How much time do you explore the e- retail store before making a purchase decision?                           5
What is your preferred payment Option?                                                                        3
How frequently do you abandon (selecting an items and leaving without making payment) your shopping cart?     4
Why did you abandon the “Bag”, “Shopping Cart”?                                                               5
The content on the website must be easy to read and understand                                                4
Information on similar product to the one highlighted  is important for product comparison                    4
Complete information on listed seller and product being offered is important for purchase decision.           5
All relevant information on listed products must be stated clearly                                            4
Ease of navigation in website                                                                                 4
Loading and processing speed                                                                                  5
User friendly Interface of the website                                                                        5
Convenient Payment methods                                                                                    3
Trust that the online retail store will fulfill its part of the transaction at the stipulated time            4
Empathy (readiness to assist with queries) towards the customers                                              4
Being able to guarantee the privacy of the customer                                                           3
Responsiveness, availability of several communication channels (email, online rep, twitter, phone etc.)       4
Online shopping gives monetary benefit and discounts                                                          5
Enjoyment is derived from shopping online                                                                     5
Shopping online is convenient and flexible                                                                    4
Return and replacement policy of the e-tailer is important for purchase decision                              3
Gaining access to loyalty programs is a benefit of shopping online                                            5
Displaying quality Information on the website improves satisfaction of customers                              3
User derive satisfaction while shopping on a good quality website or application                              3
Net Benefit derived from shopping online can lead to users satisfaction                                       4
User satisfaction cannot exist without trust                                                                  5
Offering a wide variety of listed product in several category                                                 4
Provision of complete and relevant product information                                                        4
Monetary savings                                                                                              4
The Convenience of patronizing the online retailer                                                            3
Shopping on the website gives you the sense of adventure                                                      5
Shopping on your preferred e-tailer enhances your social status                                               5
You feel gratification shopping on your favorite e-tailer                                                     5
Shopping on the website helps you fulfill certain roles                                                       5
Getting value for money spent                                                                                 3
From the following, tick any (or all) of the online retailers you have shopped from;                          9
Easy to use website or application                                                                           10
Visual appealing web-page layout                                                                             10
Wild variety of product on offer                                                                              9
Complete, relevant description information of products                                                       11
Fast loading website speed of website and application                                                        10
Reliability of the website or application                                                                    10
Quickness to complete purchase                                                                                9
Availability of several payment options                                                                      11
Speedy order delivery                                                                                         6
Privacy of customers’ information                                                                            11
Security of customer financial information                                                                   11
Perceived Trustworthiness                                                                                     9
Presence of online assistance through multi-channel                                                          10
Longer time to get logged in (promotion, sales period)                                                       10
Longer time in displaying graphics and photos (promotion, sales period)                                      10
Late declaration of price (promotion, sales period)                                                           8
Longer page loading time (promotion, sales period)                                                           11
Limited mode of payment on most products (promotion, sales period)                                            8
Longer delivery period                                                                                        6
Change in website/Application design                                                                          7
Frequent disruption when moving from one page to another                                                      8
Website is as efficient as before                                                                             8
Which of the Indian online retailer would you recommend to a friend?                                          8
dtype: int64

In [538]:
df['How old are you?'].unique()

array(['31-40 years', '21-30 years', '41-50 yaers', 'Less than 20 years',
       '51 years and above'], dtype=object)

In [539]:
data=df.copy()

In [540]:
data.head(10)

,Gender of respondent,How old are you?,Which city do you shop online from?,What is the Pin Code of where you shop online from?,Since How Long You are Shopping Online ?,How many times you have made an online purchase in the past year?,How do you access the internet while shopping on-line?,Which device do you use to access the online shopping?,What is the screen size of your mobile device?,What is the operating system (OS) of your device?,What browser do you run on your device to access the website?,Which channel did you follow to arrive at your favorite online store for the first time?,"After first visit, how do you reach the online retail store?",How much time do you explore the e- retail store before making a purchase decision?,What is your preferred payment Option?,How frequently do you abandon (selecting an items and leaving without making payment) your shopping cart?,"Why did you abandon the “Bag”, “Shopping Cart”?",The content on the website must be easy to read and understand,Information on similar product to the one highlighted is important for product comparison,Complete information on listed seller and product being offered is important for purchase decision.,All relevant information on listed products must be stated clearly,Ease of navigation in website,Loading and processing speed,User friendly Interface of the website,Convenient Payment methods,Trust that the online retail store will fulfill its part of the transaction at the stipulated time,Empathy (readiness to assist with queries) towards the customers,Being able to guarantee the privacy of the customer,"Responsiveness, availability of several communication channels (email, online rep, twitter, phone etc.)",Online shopping gives monetary benefit and discounts,Enjoyment is derived from shopping online,Shopping online is convenient and flexible,Return and replacement policy of the e-tailer is important for purchase decision,Gaining access to loyalty programs is a benefit of shopping online,Displaying quality Information on the website improves satisfaction of customers,User derive satisfaction while shopping on a good quality website or application,Net Benefit derived from shopping online can lead to users satisfaction,User satisfaction cannot exist without trust,Offering a wide variety of listed product in several category,Provision of complete and relevant product information,Monetary savings,The Convenience of patronizing the online retailer,Shopping on the website gives you the sense of adventure,Shopping on your preferred e-tailer enhances your social status,You feel gratification shopping on your favorite e-tailer,Shopping on the website helps you fulfill certain roles,Getting value for money spent,"From the following, tick any (or all) of the online retailers you have shopped from;",Easy to use website or application,Visual appealing web-page layout,Wild variety of product on offer,"Complete, relevant description information of products",Fast loading website speed of website and application,Reliability of the website or application,Quickness to complete purchase,Availability of several payment options,Speedy order delivery,Privacy of customers’ information,Security of customer financial information,Perceived Trustworthiness,Presence of online assistance through multi-channel,"Longer time to get logged in (promotion, sales period)","Longer time in displaying graphics and photos (promotion, sales period)","Late declaration of price (promotion, sales period)","Longer page loading time (promotion, sales period)","Limited mode of payment on most products (promotion, sales period)",Longer delivery period,Change in website/Application design,Frequent disruption when moving from one page to another,Website is as efficient as before,Which of the Indian online retailer would you recommend to a friend?
0,Male,31-40 years,Delhi,110009,Above 4 years,31-40 times,Dial-up,Desktop,Others,Window/windows Mobile,Google chrome,Search Engine,Search Engine,6-10 mins,"E-wallets (Paytm, Freecharge etc.)",Sometimes,Lack of trust,Agree (4),Indifferent (3),Indifferent (3),Agree (4),Agree (4),Strongly disagree (1),Dis-agree (2),Dis-agree (2),Disagree (2),Strongly agree (5),Agree (4),Agree (4),indifferent (3),Strongly disagree (1),Dis-agree (2),Dis-agree (2),Agree (4),indifferent (3),Strongly agree (5),Agree (4),Strongly agree (5),indifferent (3),indifferent (3),Disagree (2),indifferent (3),Agree (4),Agree (4),Strongly agree (5),Agree (4),Strongly agree (5),"Amazon.in, Paytm.com",Paytm.com,Flipkart.com,Flipkart.com,Snapdeal.com,Snapdeal.com,Paytm.com,Paytm.com,Patym.com,Amazon.in,Amazon.in,Amazon.in,Flipkart.com,Paytm.com,Amazon.in,Amazon.in,Flipkart.com,Flipkart.com,Amazon.in,Paytm.com,Flipkart.com,Amazon.in,Amazon.in,Flipkart.com
1,Female,21-30 years,Delhi,110030,Above 4 years,41 times and above,Wi-Fi,Smartphone,4.7 inches,IOS/Mac,Google chrome,Search Engine,Via application,more than 15 mins,Credit/Debit cards,Very frequently,Promo code not applicable,Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),indifferent (3),indifferent (3),indifferent (3),Strongly agree (5),Strongly agree (5),Strongly agree (5),"Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Myntra.com","Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Myntra.com",Myntra.com,"Amazon.com, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com",Myntra.com,Myntra.com,Myntra.com,"Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com",Myntra.com,snapdeal.com,Snapdeal.com,Snapdeal.com,Snapdeal.com,Amazon.in,Myntra.com,"Amazon.in, Flipkart.com","Amazon.in, Myntra.com"
2,Female,21-30 years,Greater Noida,201308,3-4 years,41 times and above,Mobile Internet,Smartphone,5.5 inches,Android,Google chrome,Search Engine,Via application,11-15 mins,"E-wallets (Paytm, Freecharge etc.)",Sometimes,Promo code not applicable,Strongly agree (5),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Agree (4),Agree (4),indifferent (3),indifferent (3),Agree (4),"Amazon.in, Paytm.com, Myntra.com","Amazon.in, Paytm.com, Myntra.com","Amazon.in, Paytm.com, Myntra.com","Amazon.in, Myntra.com","Amazon.in, Paytm.com, Myntra.com","Amazon.in, Paytm.com","Amazon.in, Paytm.com, Myntra.com","Amazon.com, Paytm.com, Myntra.com","Patym.com, Myntra.com",Amazon.in,Amazon.in,"Amazon.in, Paytm.com, Myntra.com","Amazon.in, Myntra.com",Myntra.com,Myntra.com,Myntra.com,Myntra.com,Myntra.com,Amazon.in,Paytm.com,Paytm.com,Paytm.com,Amazon.in,"Amazon.in, Paytm.com, Myntra.com"
3,Male,21-30 years,Karnal,132001,3-4 years,Less than 10 times,Mobile Internet,Smartphone,5.5 inches,IOS/Mac,Safari,Search Engine,Search Engine,6-10 mins,Credit/Debit cards,Never,Better alternative offer,Agree (4),Agree (4),Indifferent (3),Agree (4),Strongly agree (5),Agree (4),Strongly agree (5),Strongly agree (5),Agree (4),Strongly agree (5),Strongly agree (5),Agree (4),Agree (4),indifferent (3),indifferent (3),Agree (4),indifferent (3),indifferent (3),Agree (4),indifferent (3),Agree (4),Agree (4),Agree (4),Strongly agree (5),Agree (4),Agree (4),Strongly agree (5),Agree (4),indifferent (3),Agree (4),"Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Paytm.com","Amazon.com, Flipkart.com, Paytm.com","Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal",Snapdeal.com,"Myntra.com, Snapdeal.com",Myntra.com,Paytm.com,Paytm.com,Paytm.com,"Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com, Paytm.com","Amazon.in, Flipkart.com"
4,Female,21-30 years,Bangalore,530068,2-3 years,11-20 times,Wi-Fi,Smartphone,4.7 inches,IOS/Mac,Safari,Content Marketing,Via application,more than 15 mins,Credit/Debit cards,Frequently,Better alternative offer,Strongly agree (5),Indifferent (3),Indifferent (3),Agree (4),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Strongly agree (5),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Dis-agree (2),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Agree (4),Strongly agree (5),Agree (4),indifferent (3),Strongly disagree (1),Strongly agree (5),Strongly disagree (1),Strongly agree (5),"Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...",Myntra.com,Myntra.com,"Amazon.in, Flipkart.com, Paytm.com, Myntra.com...",Amazon.in,"Amazon.in, Paytm.com, Myntra.com","Amazon.com, Flipkart.com, Paytm.com, Myntra.co...","Amazon.in, Flipkart.com, Patym.com, Myntra.com...",Amazon.in,"Amazon.in, Paytm.com",Paytm.com,"Amazon.in, Myntra.com","Amazon.in, Myntra.com","Flipkart.com, Paytm.com",Paytm.com,Paytm.com,Paytm.com,Snapdeal.com,Paytm.com,Amazon.in,Snapdeal.com,Paytm.com,"Amazon.in, Myntra.com"
5,Female,31-40 years,Noida,201308,Above 4 years,41 times and above,Wi-Fi,Smartphone,5.5 inches,Android,Google chrome,Search Engine,Via application,more than 15 mins,"E-wallets (Paytm, Freecharge etc.)",Frequently,Better alternative offer,Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),indifferent (3),indifferent (3),Agree (4),Strongly agree (5),"Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com, Paytm.com","Amazon.in, Flipkart.com, Paytm.com","Amazon.in, Paytm.com","Amazon.in, Flipkart.com, Paytm.com, Snapdeal.com",Paytm.com,"Amazon.in, Flipkart.com, Patym.com, Myntra.com...",Amazon.in,"Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com","Flipkart.com, Paytm.com, Snapdeal.com","Amazon.in, Paytm.com","Amazon.in, Paytm.com","Amazon.in, Paytm.com","Amazon.in, Paytm.com",Flipkart.com,Paytm.com,Flipkart.com,Amazon.in,"Amazon.in, Paytm.com"
6,Male,41-50 yaers,Delhi,110011,Above 4 years,31-40 times,Wi-Fi,Tablet,Others,Android,Google chrome,Display Adverts,Direct URL,more than 15 mins,Credit/Debit cards,Sometimes,Promo code not applicable,Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Strongly agree (5),Strongly agree (5),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),indifferent (3),Agree (4),Agree (4),indifferent (3),indifferent (3),Agree (4),Agree (4),Agree (4),"Amazon.in, Flipkart.com, Paytm.com, Snapdeal.com","Amazon.in, Flipkart.com, Paytm.com, Snapdeal.com","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...",Amazon.in,"Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.com, Flipkart.com, Paytm.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal","Amazon.in, Flipkart.com, Snapdeal.com",Amazon.in,Myntra.com,Myntra.com,Flipkart.com,Snapdeal.com,Myntra.com,Myntra.com,Snapdeal.com,"Flipkart.com, Paytm.com, Myntra.com, snapdeal.com"
7,Male,41-50 yaers,Delhi,110018,3-4 years,Less than 10 times,Mobile Internet,Desktop,Others,Window/windows Mobile,Google chrome,Search Engine,E-mail,6-10 mins,Credit/Debit cards,Sometimes,Change in price,Strongly disagree (1),Dis-agree (2),Dis-agree (2),Strongly disagree (1),Strongly disagree (1),Dis-agree (2),Strongly disagree (1),Dis-agree (2),Disagree (2),Strongly disagree (1),indifferent (3),Strongly agree (5),Strongly disagree (1),Strongly disagree (1),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Strongly disagree (1),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly disagree (1),Strongly disagree (1),Strongly disagree (1),Agree (4),"Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com, Paytm.com",Amazon.in,Amazon.com,"Amazon.in, Flipkart.com",Amazon.in,Paytm.com,Flipkart.com,Amazon.in,Amazon.in,"Amazon.in, Flipkart.com","Amazon.in, Flipkart.com",Paytm.com,"Amazon.in, Flipkart.com","Amazon.in, Flipkart.com",Flipkart.com,Amazon.in,Amazon.in,Amazon.in,Amazon.in
8,Female,Less than 20 years,Solan,173229,2-3 years,Less than 10 times,Wi-Fi,Smartphone,5.5 inches,Android,Google chrome,Search Engine,Direct URL,1-5 mins,Cash on delivery (CoD),Sometimes,No preferred mode of payment,Strongly agree (5),Agree (4),Strongly agree (5),Agree (4),Agree (4),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Strongly agree (5),Agree (4),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Agree (4),Agree (4),Agree (4),indifferent (3),indifferent (3),Agree (4),indifferent (3),"Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Flipkart.com, Myntra.com, Snapdeal","Flipkart.com, Myntra.com, Snapdeal.com","Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal",Amazon.in,"Amazon.in, Myntra.com, Snapdeal.com",Amazon.in,"Amazon.in, Snapdeal.com",Amazon.in,Amazon.in,Amazon.in,"Myntra.com, Snapdeal.com","Myntra.com, Snapdeal.com",Amazon.in
9,Female,31-40 years,Delhi,110039,Less than 1 year,Less than 10 times,Wi-Fi,Laptop,Others,Window/windows Mobile,Google chrome,Search Engine,Search Engine,more than 15 mins,Cash on delivery (CoD),Sometimes,Lack of trust,Agree (4),Strongly agree (5),Agree (4),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Agree (4),Agree (4),Strongly agree (5),Agree (4),Agree (4),Agree (4),Strongly agree (5),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),indifferent (3),indifferent (3),indifferent (3),Agree (4),"Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.com, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com",Paytm.com,"Amazon.in, Flipkart.com",Paytm.com,Paytm.com,Snapdeal.com,Snapdeal.com,Myntra.com,Myntra.com,Flipkart.com,Flipkart.com

In [541]:
# Define the mapping from old column names to new ones
rename_map = {
    "Gender of respondent": "Gender",
    "How old are you?": "Age",
    "Which city do you shop online from?": "City",
    "What is the Pin Code of where you shop online from?": "PinCode",
    "Since How Long You are Shopping Online ?": "ShoppingDuration",
    "How many times you have made an online purchase in the past  year?": "PurchaseFrequency",
    "How do you access the internet while shopping on-line?": "InternetAccess",
    "Which device do you use to access the online shopping?": "Device",
    "What is the screen size of your mobile device?": "ScreenSize",
    "What is the operating system (OS) of your device?": "OS",
    "What browser do you run on your device to access the website?": "Browser",
    "Which channel did you follow to arrive at your favorite online store for the first time?": "FirstChannel",
    "After first visit, how do you reach the online retail store?": "ReturnChannel",
    "How much time do you explore the e- retail store before making a purchase decision?": "ExplorationTime",
    "What is your preferred payment Option?": "PaymentOption",
    "How frequently do you abandon (selecting an items and leaving without making payment) your shopping cart?": "CartAbandonFreq",
    "Why did you abandon the “Bag”, “Shopping Cart”?": "CartAbandonReason",
    "The content on the website must be easy to read and understand": "ContentReadability",
    "Information on similar product to the one highlighted  is important for product comparison": "ProductComparisonInfo",
    "Complete information on listed seller and product being offered is important for purchase decision.": "SellerInfoImportance",
    "All relevant information on listed products must be stated clearly": "ProductInfoClarity",
    "Ease of navigation in website": "EaseNavigation",
    "Loading and processing speed": "LoadingSpeed",
    "User friendly Interface of the website": "UserFriendlyInterface",
    "Convenient Payment methods": "ConvenientPayment",
    "Trust that the online retail store will fulfill its part of the transaction at the stipulated time": "Trust",
    "Empathy (readiness to assist with queries) towards the customers": "Empathy",
    "Being able to guarantee the privacy of the customer": "PrivacyGuarantee",
    "Responsiveness, availability of several communication channels (email, online rep, twitter, phone etc.)": "Responsiveness",
    "Online shopping gives monetary benefit and discounts": "MonetaryBenefit",
    "Enjoyment is derived from shopping online": "Enjoyment",
    "Shopping online is convenient and flexible": "Convenience",
    "Return and replacement policy of the e-tailer is important for purchase decision": "ReturnPolicy",
    "Gaining access to loyalty programs is a benefit of shopping online": "LoyaltyPrograms",
    "Displaying quality Information on the website improves satisfaction of customers": "QualityInfoSatisfaction",
    "User derive satisfaction while shopping on a good quality website or application": "WebsiteQualitySatisfaction",
    "Net Benefit derived from shopping online can lead to users satisfaction": "NetBenefitSatisfaction",
    "User satisfaction cannot exist without trust": "TrustSatisfaction",
    "Offering a wide variety of listed product in several category": "ProductVariety",
    "Provision of complete and relevant product information": "RelevantProductInfo",
    "Monetary savings": "MonetarySavings",
    "The Convenience of patronizing the online retailer": "RetailerConvenience",
    "Shopping on the website gives you the sense of adventure": "AdventureShopping",
    "Shopping on your preferred e-tailer enhances your social status": "SocialStatus",
    "You feel gratification shopping on your favorite e-tailer": "Gratification",
    "Shopping on the website helps you fulfill certain roles": "RoleFulfillment",
    "Getting value for money spent": "ValueForMoney",
    "From the following, tick any (or all) of the online retailers you have shopped from;": "Retailers",
    "Easy to use website or application": "EaseOfUse",
    "Visual appealing web-page layout": "VisualAppeal",
    "Wild variety of product on offer": "WideProductVariety",
    "Complete, relevant description information of products": "ProductDescriptionInfo",
    "Fast loading website speed of website and application": "FastLoading",
    "Reliability of the website or application": "Reliability",
    "Quickness to complete purchase": "PurchaseQuickness",
    "Availability of several payment options": "PaymentOptionsAvailability",
    "Speedy order delivery": "SpeedyDelivery",
    "Privacy of customers’ information": "Privacy",
    "Security of customer financial information": "FinancialSecurity",
    "Perceived Trustworthiness": "PerceivedTrust",
    "Presence of online assistance through multi-channel": "OnlineAssistance",
    "Longer time to get logged in (promotion, sales period)": "LoginDelayPromo",
    "Longer time in displaying graphics and photos (promotion, sales period)": "GraphicsDelayPromo",
    "Late declaration of price (promotion, sales period)": "LatePricePromo",
    "Longer page loading time (promotion, sales period)": "PageLoadDelayPromo",
    "Limited mode of payment on most products (promotion, sales period)": "LimitedPaymentPromo",
    "Longer delivery period": "DeliveryDelay",
    "Change in website/Application design": "WebsiteDesignChange",
    "Frequent disruption when moving from one page to another": "PageDisruption",
    "Website is as efficient as before": "WebsiteEfficiency",
    "Which of the Indian online retailer would you recommend to a friend?": "RecommendRetailer"
}
# Apply renaming
data.rename(columns=rename_map, inplace=True)

# Verify
print(data.columns.tolist())

['Gender', 'Age', 'City', 'PinCode', 'ShoppingDuration', 'PurchaseFrequency', 'InternetAccess', 'Device', 'ScreenSize', 'OS', 'Browser', 'FirstChannel', 'ReturnChannel', 'ExplorationTime', 'PaymentOption', 'CartAbandonFreq', 'CartAbandonReason', 'ContentReadability', 'ProductComparisonInfo', 'SellerInfoImportance', 'ProductInfoClarity', 'EaseNavigation', 'LoadingSpeed', 'UserFriendlyInterface', 'ConvenientPayment', 'Trust', 'Empathy', 'PrivacyGuarantee', 'Responsiveness', 'MonetaryBenefit', 'Enjoyment', 'Convenience', 'ReturnPolicy', 'LoyaltyPrograms', 'QualityInfoSatisfaction', 'WebsiteQualitySatisfaction', 'NetBenefitSatisfaction', 'TrustSatisfaction', 'ProductVariety', 'RelevantProductInfo', 'MonetarySavings', 'RetailerConvenience', 'AdventureShopping', 'SocialStatus', 'Gratification', 'RoleFulfillment', 'ValueForMoney', 'Retailers', 'EaseOfUse', 'VisualAppeal', 'WideProductVariety', 'ProductDescriptionInfo', 'FastLoading', 'Reliability', 'PurchaseQuickness', 'PaymentOptionsAvailability', 'SpeedyDelivery', 'Privacy', 'FinancialSecurity', 'PerceivedTrust', 'OnlineAssistance', 'LoginDelayPromo', 'GraphicsDelayPromo', 'LatePricePromo', 'PageLoadDelayPromo', 'LimitedPaymentPromo', 'DeliveryDelay', 'WebsiteDesignChange', 'PageDisruption', 'WebsiteEfficiency', 'RecommendRetailer']

In [542]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 269 entries, 0 to 268
Data columns (total 71 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Gender                      269 non-null    object
 1   Age                         269 non-null    object
 2   City                        269 non-null    object
 3   PinCode                     269 non-null    int64
 4   ShoppingDuration            269 non-null    object
 5   PurchaseFrequency           269 non-null    object
 6   InternetAccess              269 non-null    object
 7   Device                      269 non-null    object
 8   ScreenSize                  269 non-null    object
 9   OS                          269 non-null    object
 10  Browser                     269 non-null    object
 11  FirstChannel                269 non-null    object
 12  ReturnChannel               269 non-null    object
 13  ExplorationTime             269 non-null    object
 14  PaymentOption               269 non-null    object
 15  CartAbandonFreq             269 non-null    object
 16  CartAbandonReason           269 non-null    object
 17  ContentReadability          269 non-null    object
 18  ProductComparisonInfo       269 non-null    object
 19  SellerInfoImportance        269 non-null    object
 20  ProductInfoClarity          269 non-null    object
 21  EaseNavigation              269 non-null    object
 22  LoadingSpeed                269 non-null    object
 23  UserFriendlyInterface       269 non-null    object
 24  ConvenientPayment           269 non-null    object
 25  Trust                       269 non-null    object
 26  Empathy                     269 non-null    object
 27  PrivacyGuarantee            269 non-null    object
 28  Responsiveness              269 non-null    object
 29  MonetaryBenefit             269 non-null    object
 30  Enjoyment                   269 non-null    object
 31  Convenience                 269 non-null    object
 32  ReturnPolicy                269 non-null    object
 33  LoyaltyPrograms             269 non-null    object
 34  QualityInfoSatisfaction     269 non-null    object
 35  WebsiteQualitySatisfaction  269 non-null    object
 36  NetBenefitSatisfaction      269 non-null    object
 37  TrustSatisfaction           269 non-null    object
 38  ProductVariety              269 non-null    object
 39  RelevantProductInfo         269 non-null    object
 40  MonetarySavings             269 non-null    object
 41  RetailerConvenience         269 non-null    object
 42  AdventureShopping           269 non-null    object
 43  SocialStatus                269 non-null    object
 44  Gratification               269 non-null    object
 45  RoleFulfillment             269 non-null    object
 46  ValueForMoney               269 non-null    object
 47  Retailers                   269 non-null    object
 48  EaseOfUse                   269 non-null    object
 49  VisualAppeal                269 non-null    object
 50  WideProductVariety          269 non-null    object
 51  ProductDescriptionInfo      269 non-null    object
 52  FastLoading                 269 non-null    object
 53  Reliability                 269 non-null    object
 54  PurchaseQuickness           269 non-null    object
 55  PaymentOptionsAvailability  269 non-null    object
 56  SpeedyDelivery              269 non-null    object
 57  Privacy                     269 non-null    object
 58  FinancialSecurity           269 non-null    object
 59  PerceivedTrust              269 non-null    object
 60  OnlineAssistance            269 non-null    object
 61  LoginDelayPromo             269 non-null    object
 62  GraphicsDelayPromo          269 non-null    object
 63  LatePricePromo              269 non-null    object
 64  PageLoadDelayPromo          269 non-null    object
 65  LimitedPaymentPromo         269 non-null    object
 66  DeliveryDelay               269 non-null    object
 67  WebsiteDesignChange         269 non-null    object
 68  PageDisruption              269 non-null    object
 69  WebsiteEfficiency           269 non-null    object
 70  RecommendRetailer           269 non-null    object
dtypes: int64(1), object(70)
memory usage: 149.3+ KB

In [543]:
data.drop(columns=[
    "ScreenSize",
    "OS",
    "Browser",
    "WebsiteDesignChange"
],inplace=True)

In [544]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 269 entries, 0 to 268
Data columns (total 67 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Gender                      269 non-null    object
 1   Age                         269 non-null    object
 2   City                        269 non-null    object
 3   PinCode                     269 non-null    int64
 4   ShoppingDuration            269 non-null    object
 5   PurchaseFrequency           269 non-null    object
 6   InternetAccess              269 non-null    object
 7   Device                      269 non-null    object
 8   FirstChannel                269 non-null    object
 9   ReturnChannel               269 non-null    object
 10  ExplorationTime             269 non-null    object
 11  PaymentOption               269 non-null    object
 12  CartAbandonFreq             269 non-null    object
 13  CartAbandonReason           269 non-null    object
 14  ContentReadability          269 non-null    object
 15  ProductComparisonInfo       269 non-null    object
 16  SellerInfoImportance        269 non-null    object
 17  ProductInfoClarity          269 non-null    object
 18  EaseNavigation              269 non-null    object
 19  LoadingSpeed                269 non-null    object
 20  UserFriendlyInterface       269 non-null    object
 21  ConvenientPayment           269 non-null    object
 22  Trust                       269 non-null    object
 23  Empathy                     269 non-null    object
 24  PrivacyGuarantee            269 non-null    object
 25  Responsiveness              269 non-null    object
 26  MonetaryBenefit             269 non-null    object
 27  Enjoyment                   269 non-null    object
 28  Convenience                 269 non-null    object
 29  ReturnPolicy                269 non-null    object
 30  LoyaltyPrograms             269 non-null    object
 31  QualityInfoSatisfaction     269 non-null    object
 32  WebsiteQualitySatisfaction  269 non-null    object
 33  NetBenefitSatisfaction      269 non-null    object
 34  TrustSatisfaction           269 non-null    object
 35  ProductVariety              269 non-null    object
 36  RelevantProductInfo         269 non-null    object
 37  MonetarySavings             269 non-null    object
 38  RetailerConvenience         269 non-null    object
 39  AdventureShopping           269 non-null    object
 40  SocialStatus                269 non-null    object
 41  Gratification               269 non-null    object
 42  RoleFulfillment             269 non-null    object
 43  ValueForMoney               269 non-null    object
 44  Retailers                   269 non-null    object
 45  EaseOfUse                   269 non-null    object
 46  VisualAppeal                269 non-null    object
 47  WideProductVariety          269 non-null    object
 48  ProductDescriptionInfo      269 non-null    object
 49  FastLoading                 269 non-null    object
 50  Reliability                 269 non-null    object
 51  PurchaseQuickness           269 non-null    object
 52  PaymentOptionsAvailability  269 non-null    object
 53  SpeedyDelivery              269 non-null    object
 54  Privacy                     269 non-null    object
 55  FinancialSecurity           269 non-null    object
 56  PerceivedTrust              269 non-null    object
 57  OnlineAssistance            269 non-null    object
 58  LoginDelayPromo             269 non-null    object
 59  GraphicsDelayPromo          269 non-null    object
 60  LatePricePromo              269 non-null    object
 61  PageLoadDelayPromo          269 non-null    object
 62  LimitedPaymentPromo         269 non-null    object
 63  DeliveryDelay               269 non-null    object
 64  PageDisruption              269 non-null    object
 65  WebsiteEfficiency           269 non-null    object
 66  RecommendRetailer           269 non-null    object
dtypes: int64(1), object(66)
memory usage: 140.9+ KB

In [545]:
data.head()

,Gender,Age,City,PinCode,ShoppingDuration,PurchaseFrequency,InternetAccess,Device,FirstChannel,ReturnChannel,ExplorationTime,PaymentOption,CartAbandonFreq,CartAbandonReason,ContentReadability,ProductComparisonInfo,SellerInfoImportance,ProductInfoClarity,EaseNavigation,LoadingSpeed,UserFriendlyInterface,ConvenientPayment,Trust,Empathy,PrivacyGuarantee,Responsiveness,MonetaryBenefit,Enjoyment,Convenience,ReturnPolicy,LoyaltyPrograms,QualityInfoSatisfaction,WebsiteQualitySatisfaction,NetBenefitSatisfaction,TrustSatisfaction,ProductVariety,RelevantProductInfo,MonetarySavings,RetailerConvenience,AdventureShopping,SocialStatus,Gratification,RoleFulfillment,ValueForMoney,Retailers,EaseOfUse,VisualAppeal,WideProductVariety,ProductDescriptionInfo,FastLoading,Reliability,PurchaseQuickness,PaymentOptionsAvailability,SpeedyDelivery,Privacy,FinancialSecurity,PerceivedTrust,OnlineAssistance,LoginDelayPromo,GraphicsDelayPromo,LatePricePromo,PageLoadDelayPromo,LimitedPaymentPromo,DeliveryDelay,PageDisruption,WebsiteEfficiency,RecommendRetailer
0,Male,31-40 years,Delhi,110009,Above 4 years,31-40 times,Dial-up,Desktop,Search Engine,Search Engine,6-10 mins,"E-wallets (Paytm, Freecharge etc.)",Sometimes,Lack of trust,Agree (4),Indifferent (3),Indifferent (3),Agree (4),Agree (4),Strongly disagree (1),Dis-agree (2),Dis-agree (2),Disagree (2),Strongly agree (5),Agree (4),Agree (4),indifferent (3),Strongly disagree (1),Dis-agree (2),Dis-agree (2),Agree (4),indifferent (3),Strongly agree (5),Agree (4),Strongly agree (5),indifferent (3),indifferent (3),Disagree (2),indifferent (3),Agree (4),Agree (4),Strongly agree (5),Agree (4),Strongly agree (5),"Amazon.in, Paytm.com",Paytm.com,Flipkart.com,Flipkart.com,Snapdeal.com,Snapdeal.com,Paytm.com,Paytm.com,Patym.com,Amazon.in,Amazon.in,Amazon.in,Flipkart.com,Paytm.com,Amazon.in,Amazon.in,Flipkart.com,Flipkart.com,Amazon.in,Paytm.com,Amazon.in,Amazon.in,Flipkart.com
1,Female,21-30 years,Delhi,110030,Above 4 years,41 times and above,Wi-Fi,Smartphone,Search Engine,Via application,more than 15 mins,Credit/Debit cards,Very frequently,Promo code not applicable,Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),indifferent (3),indifferent (3),indifferent (3),Strongly agree (5),Strongly agree (5),Strongly agree (5),"Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Myntra.com","Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Myntra.com",Myntra.com,"Amazon.com, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com",Myntra.com,Myntra.com,Myntra.com,"Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com",Myntra.com,snapdeal.com,Snapdeal.com,Snapdeal.com,Snapdeal.com,Myntra.com,"Amazon.in, Flipkart.com","Amazon.in, Myntra.com"
2,Female,21-30 years,Greater Noida,201308,3-4 years,41 times and above,Mobile Internet,Smartphone,Search Engine,Via application,11-15 mins,"E-wallets (Paytm, Freecharge etc.)",Sometimes,Promo code not applicable,Strongly agree (5),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Agree (4),Agree (4),indifferent (3),indifferent (3),Agree (4),"Amazon.in, Paytm.com, Myntra.com","Amazon.in, Paytm.com, Myntra.com","Amazon.in, Paytm.com, Myntra.com","Amazon.in, Myntra.com","Amazon.in, Paytm.com, Myntra.com","Amazon.in, Paytm.com","Amazon.in, Paytm.com, Myntra.com","Amazon.com, Paytm.com, Myntra.com","Patym.com, Myntra.com",Amazon.in,Amazon.in,"Amazon.in, Paytm.com, Myntra.com","Amazon.in, Myntra.com",Myntra.com,Myntra.com,Myntra.com,Myntra.com,Myntra.com,Amazon.in,Paytm.com,Paytm.com,Amazon.in,"Amazon.in, Paytm.com, Myntra.com"
3,Male,21-30 years,Karnal,132001,3-4 years,Less than 10 times,Mobile Internet,Smartphone,Search Engine,Search Engine,6-10 mins,Credit/Debit cards,Never,Better alternative offer,Agree (4),Agree (4),Indifferent (3),Agree (4),Strongly agree (5),Agree (4),Strongly agree (5),Strongly agree (5),Agree (4),Strongly agree (5),Strongly agree (5),Agree (4),Agree (4),indifferent (3),indifferent (3),Agree (4),indifferent (3),indifferent (3),Agree (4),indifferent (3),Agree (4),Agree (4),Agree (4),Strongly agree (5),Agree (4),Agree (4),Strongly agree (5),Agree (4),indifferent (3),Agree (4),"Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Paytm.com","Amazon.com, Flipkart.com, Paytm.com","Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal",Snapdeal.com,"Myntra.com, Snapdeal.com",Myntra.com,Paytm.com,Paytm.com,Paytm.com,"Amazon.in, Flipkart.com","Amazon.in, Flipkart.com, Paytm.com","Amazon.in, Flipkart.com"
4,Female,21-30 years,Bangalore,530068,2-3 years,11-20 times,Wi-Fi,Smartphone,Content Marketing,Via application,more than 15 mins,Credit/Debit cards,Frequently,Better alternative offer,Strongly agree (5),Indifferent (3),Indifferent (3),Agree (4),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Strongly agree (5),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Dis-agree (2),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Agree (4),Strongly agree (5),Agree (4),indifferent (3),Strongly disagree (1),Strongly agree (5),Strongly disagree (1),Strongly agree (5),"Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...",Myntra.com,Myntra.com,"Amazon.in, Flipkart.com, Paytm.com, Myntra.com...",Amazon.in,"Amazon.in, Paytm.com, Myntra.com","Amazon.com, Flipkart.com, Paytm.com, Myntra.co...","Amazon.in, Flipkart.com, Patym.com, Myntra.com...",Amazon.in,"Amazon.in, Paytm.com",Paytm.com,"Amazon.in, Myntra.com","Amazon.in, Myntra.com","Flipkart.com, Paytm.com",Paytm.com,Paytm.com,Paytm.com,Snapdeal.com,Paytm.com,Snapdeal.com,Paytm.com,"Amazon.in, Myntra.com"

In [546]:
data['Age'].unique()[:20]

array(['31-40 years', '21-30 years', '41-50 yaers', 'Less than 20 years',
       '51 years and above'], dtype=object)

In [547]:
data['ShoppingDuration'].unique()[:20]

array(['Above 4 years', '3-4 years', '2-3 years', 'Less than 1 year',
       '1-2 years'], dtype=object)

In [548]:
data['PurchaseFrequency'].unique()[:20]

array(['31-40 times', '41 times and above', 'Less than 10 times',
       '11-20 times', '21-30 times', '42 times and above'], dtype=object)

In [549]:
data['Enjoyment'].unique()[:30]

array(['Strongly disagree (1)', 'Strongly agree (5)', 'indifferent (3)',
       'Agree (4)', 'Dis-agree (2)'], dtype=object)

In [550]:
# Define mapping for Age ranges
age_map = {
    "Less than 20 years": 18,
    "21-30 years": 25,
    "31-40 years": 35,
    "41-50 yaers": 45,   # note typo "yaers" in your data
    "51 years and above": 55
}

# Apply mapping
data["Age"] = data["Age"].map(age_map)

# Check results
print(data["Age"].unique())

[35 25 45 18 55]

In [551]:
duration_map = {
    "Less than 1 year": 0.5,
    "1-2 years": 1.5,
    "2-3 years": 2.5,
    "3-4 years": 3.5,
    "Above 4 years": 5   # or 4.5 if you prefer midpoint
}

data["ShoppingDuration"] = data["ShoppingDuration"].map(duration_map)

In [552]:
# Define mapping for PurchaseFrequency ranges
freq_map = {
    "Less than 10 times": 9.5,       # midpoint just below 10
    "11-20 times": 15.5,             # midpoint
    "21-30 times": 25.5,
    "31-40 times": 35.5,
    "41 times and above": 41.5,      # just above 41
    "42 times and above": 42.5       # just above 42
}

# Apply mapping
data["PurchaseFrequency"] = data["PurchaseFrequency"].map(freq_map)

# Check results
print(data[["PurchaseFrequency"]].head())

   PurchaseFrequency
0               35.5
1               41.5
2               41.5
3                9.5
4               15.5

In [553]:
data["Age"] = pd.to_numeric(data["Age"], errors="coerce")

In [554]:
data["PurchaseFrequency"] = pd.to_numeric(data["PurchaseFrequency"], errors="coerce")

In [555]:
data.head()

,Gender,Age,City,PinCode,ShoppingDuration,PurchaseFrequency,InternetAccess,Device,FirstChannel,ReturnChannel,ExplorationTime,PaymentOption,CartAbandonFreq,CartAbandonReason,ContentReadability,ProductComparisonInfo,SellerInfoImportance,ProductInfoClarity,EaseNavigation,LoadingSpeed,UserFriendlyInterface,ConvenientPayment,Trust,Empathy,PrivacyGuarantee,Responsiveness,MonetaryBenefit,Enjoyment,Convenience,ReturnPolicy,LoyaltyPrograms,QualityInfoSatisfaction,WebsiteQualitySatisfaction,NetBenefitSatisfaction,TrustSatisfaction,ProductVariety,RelevantProductInfo,MonetarySavings,RetailerConvenience,AdventureShopping,SocialStatus,Gratification,RoleFulfillment,ValueForMoney,Retailers,EaseOfUse,VisualAppeal,WideProductVariety,ProductDescriptionInfo,FastLoading,Reliability,PurchaseQuickness,PaymentOptionsAvailability,SpeedyDelivery,Privacy,FinancialSecurity,PerceivedTrust,OnlineAssistance,LoginDelayPromo,GraphicsDelayPromo,LatePricePromo,PageLoadDelayPromo,LimitedPaymentPromo,DeliveryDelay,PageDisruption,WebsiteEfficiency,RecommendRetailer
0,Male,35,Delhi,110009,5.0,35.5,Dial-up,Desktop,Search Engine,Search Engine,6-10 mins,"E-wallets (Paytm, Freecharge etc.)",Sometimes,Lack of trust,Agree (4),Indifferent (3),Indifferent (3),Agree (4),Agree (4),Strongly disagree (1),Dis-agree (2),Dis-agree (2),Disagree (2),Strongly agree (5),Agree (4),Agree (4),indifferent (3),Strongly disagree (1),Dis-agree (2),Dis-agree (2),Agree (4),indifferent (3),Strongly agree (5),Agree (4),Strongly agree (5),indifferent (3),indifferent (3),Disagree (2),indifferent (3),Agree (4),Agree (4),Strongly agree (5),Agree (4),Strongly agree (5),"Amazon.in, Paytm.com",Paytm.com,Flipkart.com,Flipkart.com,Snapdeal.com,Snapdeal.com,Paytm.com,Paytm.com,Patym.com,Amazon.in,Amazon.in,Amazon.in,Flipkart.com,Paytm.com,Amazon.in,Amazon.in,Flipkart.com,Flipkart.com,Amazon.in,Paytm.com,Amazon.in,Amazon.in,Flipkart.com
1,Female,25,Delhi,110030,5.0,41.5,Wi-Fi,Smartphone,Search Engine,Via application,more than 15 mins,Credit/Debit cards,Very frequently,Promo code not applicable,Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),indifferent (3),indifferent (3),indifferent (3),Strongly agree (5),Strongly agree (5),Strongly agree (5),"Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal.com","Amazon.in, Myntra.com","Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Myntra.com",Myntra.com,"Amazon.com, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com",Myntra.com,Myntra.com,Myntra.com,"Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com",Myntra.com,snapdeal.com,Snapdeal.com,Snapdeal.com,Snapdeal.com,Myntra.com,"Amazon.in, Flipkart.com","Amazon.in, Myntra.com"
2,Female,25,Greater Noida,201308,3.5,41.5,Mobile Internet,Smartphone,Search Engine,Via application,11-15 mins,"E-wallets (Paytm, Freecharge etc.)",Sometimes,Promo code not applicable,Strongly agree (5),Agree (4),Agree (4),Agree (4),Agree (4),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Agree (4),Agree (4),indifferent (3),indifferent (3),Agree (4),"Amazon.in, Paytm.com, Myntra.com","Amazon.in, Paytm.com, Myntra.com","Amazon.in, Paytm.com, Myntra.com","Amazon.in, Myntra.com","Amazon.in, Paytm.com, Myntra.com","Amazon.in, Paytm.com","Amazon.in, Paytm.com, Myntra.com","Amazon.com, Paytm.com, Myntra.com","Patym.com, Myntra.com",Amazon.in,Amazon.in,"Amazon.in, Paytm.com, Myntra.com","Amazon.in, Myntra.com",Myntra.com,Myntra.com,Myntra.com,Myntra.com,Myntra.com,Amazon.in,Paytm.com,Paytm.com,Amazon.in,"Amazon.in, Paytm.com, Myntra.com"
3,Male,25,Karnal,132001,3.5,9.5,Mobile Internet,Smartphone,Search Engine,Search Engine,6-10 mins,Credit/Debit cards,Never,Better alternative offer,Agree (4),Agree (4),Indifferent (3),Agree (4),Strongly agree (5),Agree (4),Strongly agree (5),Strongly agree (5),Agree (4),Strongly agree (5),Strongly agree (5),Agree (4),Agree (4),indifferent (3),indifferent (3),Agree (4),indifferent (3),indifferent (3),Agree (4),indifferent (3),Agree (4),Agree (4),Agree (4),Strongly agree (5),Agree (4),Agree (4),Strongly agree (5),Agree (4),indifferent (3),Agree (4),"Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Paytm.com","Amazon.com, Flipkart.com, Paytm.com","Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Snapdeal.com","Amazon.in, Flipkart.com, Myntra.com, Snapdeal",Snapdeal.com,"Myntra.com, Snapdeal.com",Myntra.com,Paytm.com,Paytm.com,Paytm.com,"Amazon.in, Flipkart.com","Amazon.in, Flipkart.com, Paytm.com","Amazon.in, Flipkart.com"
4,Female,25,Bangalore,530068,2.5,15.5,Wi-Fi,Smartphone,Content Marketing,Via application,more than 15 mins,Credit/Debit cards,Frequently,Better alternative offer,Strongly agree (5),Indifferent (3),Indifferent (3),Agree (4),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Strongly agree (5),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Strongly agree (5),Dis-agree (2),Agree (4),Strongly agree (5),Strongly agree (5),Strongly agree (5),Agree (4),Agree (4),Strongly agree (5),Agree (4),indifferent (3),Strongly disagree (1),Strongly agree (5),Strongly disagree (1),Strongly agree (5),"Amazon.in, Flipkart.com, Paytm.com, Myntra.com...","Amazon.in, Flipkart.com, Paytm.com, Myntra.com...",Myntra.com,Myntra.com,"Amazon.in, Flipkart.com, Paytm.com, Myntra.com...",Amazon.in,"Amazon.in, Paytm.com, Myntra.com","Amazon.com, Flipkart.com, Paytm.com, Myntra.co...","Amazon.in, Flipkart.com, Patym.com, Myntra.com...",Amazon.in,"Amazon.in, Paytm.com",Paytm.com,"Amazon.in, Myntra.com","Amazon.in, Myntra.com","Flipkart.com, Paytm.com",Paytm.com,Paytm.com,Paytm.com,Snapdeal.com,Paytm.com,Snapdeal.com,Paytm.com,"Amazon.in, Myntra.com"

In [556]:
data['Age'].isnull().sum()

np.int64(0)

In [557]:
data['ShoppingDuration'].isnull().sum()

np.int64(0)

In [558]:
data['PurchaseFrequency'].isnull().sum()

np.int64(0)

In [559]:
data['Enjoyment'].isnull().sum()

np.int64(0)

In [560]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 269 entries, 0 to 268
Data columns (total 67 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Gender                      269 non-null    object
 1   Age                         269 non-null    int64
 2   City                        269 non-null    object
 3   PinCode                     269 non-null    int64
 4   ShoppingDuration            269 non-null    float64
 5   PurchaseFrequency           269 non-null    float64
 6   InternetAccess              269 non-null    object
 7   Device                      269 non-null    object
 8   FirstChannel                269 non-null    object
 9   ReturnChannel               269 non-null    object
 10  ExplorationTime             269 non-null    object
 11  PaymentOption               269 non-null    object
 12  CartAbandonFreq             269 non-null    object
 13  CartAbandonReason           269 non-null    object
 14  ContentReadability          269 non-null    object
 15  ProductComparisonInfo       269 non-null    object
 16  SellerInfoImportance        269 non-null    object
 17  ProductInfoClarity          269 non-null    object
 18  EaseNavigation              269 non-null    object
 19  LoadingSpeed                269 non-null    object
 20  UserFriendlyInterface       269 non-null    object
 21  ConvenientPayment           269 non-null    object
 22  Trust                       269 non-null    object
 23  Empathy                     269 non-null    object
 24  PrivacyGuarantee            269 non-null    object
 25  Responsiveness              269 non-null    object
 26  MonetaryBenefit             269 non-null    object
 27  Enjoyment                   269 non-null    object
 28  Convenience                 269 non-null    object
 29  ReturnPolicy                269 non-null    object
 30  LoyaltyPrograms             269 non-null    object
 31  QualityInfoSatisfaction     269 non-null    object
 32  WebsiteQualitySatisfaction  269 non-null    object
 33  NetBenefitSatisfaction      269 non-null    object
 34  TrustSatisfaction           269 non-null    object
 35  ProductVariety              269 non-null    object
 36  RelevantProductInfo         269 non-null    object
 37  MonetarySavings             269 non-null    object
 38  RetailerConvenience         269 non-null    object
 39  AdventureShopping           269 non-null    object
 40  SocialStatus                269 non-null    object
 41  Gratification               269 non-null    object
 42  RoleFulfillment             269 non-null    object
 43  ValueForMoney               269 non-null    object
 44  Retailers                   269 non-null    object
 45  EaseOfUse                   269 non-null    object
 46  VisualAppeal                269 non-null    object
 47  WideProductVariety          269 non-null    object
 48  ProductDescriptionInfo      269 non-null    object
 49  FastLoading                 269 non-null    object
 50  Reliability                 269 non-null    object
 51  PurchaseQuickness           269 non-null    object
 52  PaymentOptionsAvailability  269 non-null    object
 53  SpeedyDelivery              269 non-null    object
 54  Privacy                     269 non-null    object
 55  FinancialSecurity           269 non-null    object
 56  PerceivedTrust              269 non-null    object
 57  OnlineAssistance            269 non-null    object
 58  LoginDelayPromo             269 non-null    object
 59  GraphicsDelayPromo          269 non-null    object
 60  LatePricePromo              269 non-null    object
 61  PageLoadDelayPromo          269 non-null    object
 62  LimitedPaymentPromo         269 non-null    object
 63  DeliveryDelay               269 non-null    object
 64  PageDisruption              269 non-null    object
 65  WebsiteEfficiency           269 non-null    object
 66  RecommendRetailer           269 non-null    object
dtypes: float64(2), int64(2), object(63)
memory usage: 140.9+ KB